In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
torch.linspace(0, 1, 5) #similar to np

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [3]:
torch.arange(50).reshape(2,5,5) #also similar to np

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]])

In [4]:
np.arange(50).reshape(2,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [5]:
torch.zeros(5,5) #also torch.ones

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
A = torch.rand(5,5) # same as np.random.rand(5,5)
B = torch.randn(5,5)
torch.matmul(A, B) # torch.dot only for 1D tensors

tensor([[-0.5438, -0.1971, -1.4771, -0.6363,  3.1291],
        [-0.2986, -1.4392, -0.9978, -0.0076,  3.1693],
        [-0.3628, -0.5556, -0.5868, -0.2115,  3.8937],
        [ 0.3224,  0.4790, -0.7414, -0.3546,  1.8653],
        [-1.4843,  0.0846, -0.9541, -0.7514,  2.9856]])

In [7]:
C = torch.rand(5).reshape((1,5))
C_ = A + C
torch.sum(C_, axis = 0) #again, very similar to np

tensor([4.0509, 6.5311, 3.9779, 6.8514, 6.5269])

In [8]:
img = torch.randn((256, 256, 3))
scaling = torch.tensor([0.5, 1.5, 0.7]) #Typical np.array
img * scaling

tensor([[[ 0.7248, -1.7073, -0.9236],
         [-0.2662,  0.3143, -0.8720],
         [ 0.2256,  0.1684, -1.0515],
         ...,
         [ 0.5077,  1.0369,  0.2821],
         [ 0.5596, -0.7003,  0.5801],
         [ 0.7481,  0.7275, -0.3850]],

        [[-0.0236,  0.8585,  0.1203],
         [-0.2486, -1.0642, -0.3083],
         [-0.1735,  1.0117,  0.5837],
         ...,
         [-1.0136,  1.1023,  0.8792],
         [ 0.8258, -1.8024, -1.2333],
         [ 0.6644, -2.0358,  0.1350]],

        [[ 0.3718,  0.5594, -1.0722],
         [ 0.1261,  1.8579, -0.4502],
         [-0.0846,  3.3476,  0.1255],
         ...,
         [-0.2601,  0.1306, -0.6902],
         [-0.2644, -0.5267, -1.0153],
         [-0.6003,  2.7376, -1.0467]],

        ...,

        [[ 1.2764, -1.0423, -1.4951],
         [ 0.9480, -0.6920, -1.0622],
         [-0.0635, -1.4017,  0.1289],
         ...,
         [ 0.2785,  1.2378,  0.8129],
         [ 0.0617,  1.3541, -2.1059],
         [ 0.4024,  2.0220,  1.2545]],

        [[

In [9]:
# If one does 3 imgs
Imgs = torch.randn((3, 256, 256, 3))
Scaling = torch.tensor([1,3,1,3,2,5,6,7,1]).reshape(3, 1, 1, 3)
Imgs * Scaling #Same idea with the broadcasting
# Very similar to np

tensor([[[[-5.8535e-01,  4.9327e-01, -1.4508e+00],
          [ 1.2300e+00,  2.3255e+00,  7.7679e-01],
          [ 2.4060e-01, -6.2615e+00,  8.8947e-01],
          ...,
          [-1.5444e+00,  1.3815e+00,  2.4006e-01],
          [-1.0655e+00,  6.2325e-01,  2.9279e-01],
          [-2.2712e-01,  3.0128e-01,  5.2110e-01]],

         [[-6.5719e-01,  2.9897e-01, -3.2980e-01],
          [-1.8480e+00, -2.8818e+00, -9.4673e-02],
          [-7.5209e-01, -3.6095e+00, -1.3619e+00],
          ...,
          [-1.3014e-01,  3.8813e+00,  7.8114e-01],
          [-1.8890e+00, -4.4881e+00,  3.6701e-01],
          [-4.5814e-01, -6.0741e+00,  1.1014e+00]],

         [[ 1.3063e+00,  1.4298e+00,  1.7238e-01],
          [ 3.8371e-01, -8.9982e-01,  5.0473e-01],
          [-1.1132e+00,  2.1745e-01,  8.1353e-01],
          ...,
          [ 1.1483e+00,  5.0932e+00,  1.0662e+00],
          [ 3.2541e-01,  5.2651e+00, -5.2901e-01],
          [-1.2002e+00,  5.0344e+00,  3.6206e-01]],

         ...,

         [[-1.10

In [10]:
a = torch.tensor([1.,2.,3.])
torch.mean(a)

tensor(2.)

In [11]:
torch.std(a)

tensor(1.)

In [12]:
a = torch.arange(10, dtype = float).reshape(2,5)
torch.mean(a, axis = 1)

tensor([2., 7.], dtype=torch.float64)

In [17]:
### Unto the interesting stuff (Autograd!)

x = torch.randn((2,5), requires_grad = True)
y = (x**2 / 2).sum()
y.backward() # compute grad
x.grad #(grad of y wrt x)

tensor([[ 1.0376,  1.1902,  0.3847,  0.9979,  0.2799],
        [-0.8382, -0.6938,  0.1442, -0.5453,  0.1968]])